run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

issues:
  exclude-rules:
    # Exclude all linters from test files
    - path: _test\.go
      linters:
        - errcheck

  exclude:
    # Ignore Close errors in defer statements
    - "Error return value of.*Close.*is not checked"
