version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  errcheck:
    check-blank: false
    ignore: Close

issues:
  exclude-rules:
    # Exclude all linters from test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
